### ISSUE TITLE
FOR RACHEL: PLEASE PROVIDE AN EMAIL TEMPLATE

### ISSUE THREAD

**Issue by teenie-quaggard** [the-advocacy-project/advocacy-app#36]
HI Rachel,

One thing that we will need in the future is how you will like email to be formatted when the overview is sent out.

Thank you!

**Comment by rachel-butt** [comment]
Hi!

OK no problem :) maybe we can discuss this tomorrow so I understand what is needed fully.

Hope you guys are having fun! Sending positive power and gong sounds x

**Comment by rachel-butt** [comment]
Email Template draft 1

Dear local authority decision maker, 

Please accept this referral to Adult Social Care on behalf of the named client. 

Please consider the evidence outlined in this document and fulfil the appropriate duty to provide: 

1. A Care Act Assessment 
S.9 (1) Care Act 2014

http://www.legislation.gov.uk/ukpga/2014/23/section/9/enacted

2.An Independent Care Act Advocate 
S.67 Care Act 2014

https://www.legislation.gov.uk/ukpga/2014/23/section/67 

Please note the advocacy duty applies from the first point of contact with the local authority + any subsequent stage of the assessment, planning, care review ect. 

The local authority must arrange an Independent Care Act Advocate to facilitate the involvement of a person in their assessment, in the preparation of their care and support plan and in the review of their care plan in two conditions are met:

(1)	That if an independent advocate were not provided the person would have substantial difficulty in being fully involved in the process.
(2)	There is no appropriate individual available to support and represent the person’s wishes who is not paid or professionally engaged in providing care or treatment to the person or their carer.

Warm Regards,

The Advocacy Project 

https://www.advocacyproject.org.uk/advocacy-referrals/ 

NB: we may need to add a sentence on 'contact the client or the advocacy project for further information to determine duty if required'
