### ISSUE TITLE
FOR RACHEL: PLEASE DEFINE KEY RIGHTS

### ISSUE THREAD

**Issue by teenie-quaggard** [the-advocacy-project/advocacy-app#38]
Hi Rachel,

It would be great if you could define the key right for us to include on the info page.

Thank you!

**Comment by rachel-butt** [comment]
Key Rights + Duties

The Care Act 2014 

**Right to a Care Act Assessment** 

S.9 Assessment of an adult’s needs for care and support

(1)Where it appears to a local authority that an adult may have needs for care and support, the authority must assess—

(a)whether the adult does have needs for care and support, and

(b)if the adult does, what those needs are.

(2)An assessment under subsection (1) is referred to in this Part as a “needs assessment”.

(3)The duty to carry out a needs assessment applies regardless of the authority’s view of—

(a)the level of the adult’s needs for care and support, or

(b)the level of the adult’s financial resources.

http://www.legislation.gov.uk/ukpga/2014/23/section/9/enacted 

**Eligibility for Support** 

The local authority will determine if you are eligible for support by considering three requirements:

1. Your needs must be the result of a physical or mental impairment or illness
2. As a result you must be unable to achieve two or more of the outcomes set out in 
the eligibility criteria, and
3.As a consequence there is likely to be a significant impact on your well being

**Duty to provide a Care Act advocate** 

S. 67 Involvement in assessments, plans etc.

(1)This section applies where a local authority is required by a relevant provision to involve an individual in its exercise of a function.

(2)The authority must, if the condition in subsection (4) is met, arrange for a person who is independent of the authority (an “independent advocate”) to be available to represent and support the individual for the purpose of facilitating the individual's involvement;

https://www.legislation.gov.uk/ukpga/2014/23/section/67

The condition in subsection 4 is outlined in statutory guidance:

''7.4 Local authorities must arrange an independent advocate to facilitate the involvement of a person in their assessment, in the preparation of their care and support plan and in the review of their care plan, as well as in safeguarding enquiries and SARs if 2 conditions are met. 

That if an independent advocate were not provided then the person would have substantial difficulty in being fully involved in these processes and second, there is no appropriate individual available to support and represent the person’s wishes who is not paid or professionally engaged in providing care or treatment to the person or their carer. 

The role of the independent advocate is to support and represent the person and to facilitate their involvement in the key processes and interactions with the local authority.''

https://www.gov.uk/government/publications/care-act-statutory-guidance/care-and-support-statutory-guidance

A summerised version of S.67 here:

S.67 highlights a duty to provide independent advocacy support where the authority considers that:
(1) you would have ‘substantial difficulty’ in being involved in your assessment, the preparation of your 
care and support plan or other processes about care provision (including care reviews, safeguarding 
enquiries and safeguarding adult reviews; and
(2) there is no one appropriate available to support you with the process.

**Comment by rachel-butt** [comment]
Link for Eligibility: 

https://www.scie.org.uk/care-act-2014/assessment-and-eligibility/eligibility/outcomes-care-support-needs.asp

**Comment by rachel-butt** [comment]
Key Rights + Duties

The Care Act 2014

**Right to a Care Act Assessment**

S.9 Assessment of an adult’s needs for care and support

(1)Where it appears to a local authority that an adult may have needs for care and support, the authority must assess—

(a)whether the adult does have needs for care and support, and

(b)if the adult does, what those needs are.

(2)An assessment under subsection (1) is referred to in this Part as a “needs assessment”.

(3)The duty to carry out a needs assessment applies regardless of the authority’s view of—

(a)the level of the adult’s needs for care and support, or

(b)the level of the adult’s financial resources.

http://www.legislation.gov.uk/ukpga/2014/23/section/9/enacted

**Duty to provide Support**

The local authority have a duty to provide support if three requirements are met:

    1. Your needs must be the result of a physical or mental impairment or illness

    2. As a result you must be unable to achieve two or more of the outcomes set out in
       the eligibility criteria, and

    3.As a consequence there is likely to be a significant impact on your well being


**Duty to provide a Care Act advocate**

S.67  Duty to provide independent advocacy support where the authority considers that:
(1) you would have ‘substantial difficulty’ in being involved in your assessment, the preparation of your
care and support plan or other processes about care provision (including care reviews, safeguarding
enquiries and safeguarding adult reviews; and
(2) there is no one appropriate available to support you with the process.

The role of the independent advocate is to support and represent the person and to facilitate their involvement in the key processes and interactions with the local authority.

More details included in Statutory Guidance at point 7.4 on the link below:

https://www.gov.uk/government/publications/care-act-statutory-guidance/care-and-support-statutory-guidance
