### ISSUE TITLE
FOR RACHEL: COPY TO REVIEW

### ISSUE THREAD

**Issue by teenie-quaggard** [the-advocacy-project/advocacy-app#42]
[The Advocacy Project Copy.docx](https://github.com/the-advocacy-project/advocacy-app/files/2843079/The.Advocacy.Project.Copy.docx)

**Comment by rachel-butt** [comment]
Thanks for this guys! I am sending it to branding colleague now and will take her feedback and confirm the exact wording this afternoon.

**Comment by rachel-butt** [comment]
[The.Advocacy.Project.Copy.docx](https://github.com/the-advocacy-project/advocacy-app/files/2851633/The.Advocacy.Project.Copy.docx)

**Comment by rachel-butt** [comment]
Hi guys! Here is suggested edit of the copy. I've had some really helpful input from branding and hopefully this is a little more streamline. 

There may be bits to wiggle around but I'm hoping this is clear and a solid structure to get coding with! 

Big love to you all xx
