### ISSUE TITLE
What is Advocacy?

### ISSUE THREAD

**Issue by rachel-butt** [the-advocacy-project/advocacy-app#47]
Definition of advocacy:

Advocacy is taking action to help people say what they want, secure their rights, represent their interests and obtain services they need. Advocates and advocacy providers work in partnership with the people they support and take their side. Advocacy promotes social inclusion, equality and social justice. 

https://qualityadvocacy.org.uk/wp-content/uploads/2018/05/Code-of-Practice-1.pdf

**Comment by teenie-quaggard** [comment]
On figma
