### ISSUE TITLE
What is the Care Act?

### ISSUE THREAD

**Issue by rachel-butt** [the-advocacy-project/advocacy-app#48]
''The Care Act 2014 sets out in one place, local authorities’ duties in relation to assessing people’s needs and their eligibility for publicly funded care and support.

Under the Care Act 2014, local authorities must:

carry out an assessment of anyone who appears to require care and support, regardless of their likely eligibility for state-funded care.

focus the assessment on the person’s needs and how they impact on their wellbeing, and the outcomes they want to achieve.

involve the person in the assessment and, where appropriate, their carer or someone else they nominate provide access to an independent advocate to support the person’s involvement in the assessment if required.''

The Social Care Institue for Excellence

https://www.scie.org.uk/care-act-2014/assessment-and-eligibility/

**Comment by teenie-quaggard** [comment]
Included in Figma
