### ISSUE TITLE
FOR RACHEL: RESCHEDULE TESTING FOR EARLY NEXT WEEK

### ISSUE THREAD

**Issue by teenie-quaggard** [the-advocacy-project/advocacy-app#56]
Hi Rachel, 

I just wanted to ask if it were possible to reschedule the testing for next week instead of Thursday. We have been taking a lot of time to plan which is excellent because we will have less issues later on, but it would be great if we could push testing to have a more complete app to test. Testing this Thursday may not be as fruitful since we will have less complete. I thought it may give you a bit of time to rest as well. Do let me know! 

Thank you!
x

**Comment by rachel-butt** [comment]
Hey! Yes no problem at all. Lets cancel this Thursday and leave it with me to re-arrange for next week.

At the moment I am free next Tue 1-3pm. 

I am trying to get some service users involved and will let you know asap if that works your end?

Great work on the planning! :D 

I'll be back for the other issues later today x

**Comment by teenie-quaggard** [comment]
Thanks Rachel - Tuesday 1-3 is perfect!

**Comment by rachel-butt** [comment]
Hey! OK ace :) I'm afraid the last users are in another meeting but I am coordinating some peer mentors from the same project, and some new advocates/vols who will fit the spec!

**Comment by teenie-quaggard** [comment]
That's amazing. Thank you - see you then!
